---
- name: Basic Setup
  hosts: all
  become: yes
  tags:
    - base
  vars_files:
    - vars.yml
  roles:
    - base
    - ubuntu-unattended-upgrades

- name: Rocketchat
  hosts: all
  become: yes
  vars_files:
    - vars.yml
  tags:
    - rocketchat
  vars:
    nginx_domain_name: "chat.{{ main_domain }}"
  roles:
    - nginx
    - nginx-tls-add
    - docker
    - rocketchat

- name: Whiteboard
  hosts: all
  become: yes
  vars_files:
    - vars.yml
  tags:
    - whiteboard
  vars:
    nginx_domain_name: "tafel.{{ main_domain }}"
  roles:
    - nginx
    - nginx-tls-add
    - docker
    - whiteboard

- name: Jitsi
  collections:
    - community.docker
  hosts:
    - all
  become: yes
  tags:
    - jitsi
    - never
  vars_files:
    - vars.yml
  vars:
    nginx_domain_name: "jitsi.{{ main_domain }}"
    docker_config_project: jitsi
    project_root: /srv/jitsi
  roles:
    - nginx
    - nginx-tls-add
    - docker
    - jitsi

- name: Cryptpad
  hosts: all
  become: yes
  vars_files:
    - vars.yml
  tags:
    - cryptpad
  vars:
    nginx_domain_name: "cryptpad.{{ main_domain }}"
  roles:
    - nginx
    - nginx-tls-add
    - docker
    - cryptpad

- name: Mumble
  hosts: all
  become: yes
  vars_files:
    - vars.yml
  tags:
    - mumble
  vars:
    nginx_domain_name: "mumble.{{ main_domain }}"
  roles:
    - nginx
    - nginx-tls-add
    - docker
    - mumble

- name: Collabora
  hosts: all
  become: yes
  vars_files:
    - vars.yml
  tags:
    - collabora
  vars:
    nginx_domain_name: "collabora.{{ main_domain }}"
  roles:
    - nginx
    - nginx-tls-add
    - docker
    - collabora

- name: Deploy mailserver
  collections:
    - community.docker
  hosts: 
    - all
  become: yes
  tags:
    - mail
    - never
  vars_files:
    - vars.yml
  vars:
    main_domain_name: "{{ main_domain }}"
    restic_to_backup: "/srv/mailserver"
    project_root: "/srv/mailserver"
  roles:
    - restic
    - docker
    - mailserver

- name: Ensure restic
  hosts: all
  become: yes
  tags: restic
  roles:
    - restic

- name: Start the most important docker containers
  hosts: all
  become: yes
  vars_files:
    - vars.yml
  tags: [ 'never', 'startdockers' ]
  roles:
    - docker
    - dockercomposeup

- name: Secure the ssh server
  hosts: all
  become: yes
  vars_files:
    - vars.yml
  tags: [ 'never', 'security' ]
  roles:
    - security

- name: Perform backup
  hosts: all
  become: yes
  vars:
    restic_to_backup: /srv
  tags: [ 'never', 'backup' ]
  roles:
    - restic