---
- name: Basic Setup
  hosts: all
  become: yes
  tags:
    - base
  vars_files:
    - vars.yml
  roles:
    - base

- name: Rocketchat
  hosts: all
  become: yes
  vars_files:
    - vars.yml
  tags:
    - rocketchat
  vars:
    nginx_domain_name: "chat.{{ main_domain }}"
  roles:
    - nginx
    - nginx-tls-add
    - docker
    - rocketchat

- name: Whiteboard
  hosts: all
  become: yes
  vars_files:
    - vars.yml
  tags:
    - whiteboard
  vars:
    nginx_domain_name: "tafel.{{ main_domain }}"
  roles:
    - nginx
    - nginx-tls-add
    - docker
    - whiteboard

- name: Jitsi
  hosts: all
  become: yes
  vars_files:
    - vars.yml
  tags:
    - jitsi
  vars:
    nginx_domain_name: "jitsi.{{ main_domain }}"
  roles:
    - nginx
    - nginx-tls-add
    - docker
    - jitsi

- name: Cryptpad
  hosts: all
  become: yes
  vars_files:
    - vars.yml
  tags:
    - cryptpad
  vars:
    nginx_domain_name: "cryptpad.{{ main_domain }}"
  roles:
    - nginx
    - nginx-tls-add
    - docker
    - cryptpad

- name: Mumble
  hosts: all
  become: yes
  vars_files:
    - vars.yml
  tags:
    - mumble
  vars:
    domain_name: "mumble.{{ main_domain }}"
  roles:
    - docker
    - mumble

- name: Collabora
  hosts: all
  become: yes
  vars_files:
    - vars.yml
  tags:
    - collabora
  vars:
    nginx_domain_name: "collabora.{{ main_domain }}"
  roles:
    - nginx
    - nginx-tls-add
    - docker
    - collabora

- name: Watchtower
  hosts: all
  become: yes
  vars_files:
    - vars.yml
  tags:
    - watchtower
  roles:
    - docker
    - watchtower

- name: Start the most important docker containers
  hosts: all
  become: yes
  vars_files:
    - vars.yml
  tags: [ 'never', 'startdockers' ]
  roles:
    - docker
    - dockercomposeup

- name: Secure the ssh server
  hosts: all
  become: yes
  vars_files:
    - vars.yml
  tags: [ 'never', 'security' ]
  roles:
    - security
