---
- name: Basic Setup
  hosts: localhost
  connection: local 
  become: yes
  tags:
    - base
  vars_files:
    - vars.yml
  roles:
    - base
    - docker
    - nginx
    - restic
    - ubuntu-unattended-upgrades

- name: Rocketchat
  hosts: localhost
  connection: local 
  become: yes
  vars_files:
    - vars.yml
  tags:
    - rocketchat
    - never
  vars:
    nginx_domain_name: "chat.{{ main_domain }}"
    upload_limit: 500M
    project_root: /srv/rocketchat
    restic_to_backup: "/srv/rocketchat"
  roles:
    - restic
    - nginx-tls-add
    - rocket

- name: Whiteboard
  hosts: localhost
  connection: local 
  become: yes
  vars_files:
    - vars.yml
  tags:
    - whiteboard
    - never
  vars:
    nginx_domain_name: "tafel.{{ main_domain }}"
  roles:
    - nginx-tls-add
    - whiteboard

- name: Jitsi
  hosts: localhost
  connection: local 
  become: yes
  tags:
    - jitsi
    - never
  vars_files:
    - vars.yml
  vars:
    nginx_domain_name: "jitsi.{{ main_domain }}"
    docker_config_project: jitsi
    project_root: /srv/jitsi
  roles:
    - nginx-tls-add
    - tna76874.ansible_docker_jitsi

- name: Cryptpad
  hosts: localhost
  connection: local 
  become: yes
  vars_files:
    - vars.yml
  tags:
    - cryptpad
    - never
  vars:
    nginx_domain_name: "cryptpad.{{ main_domain }}"
  roles:
    - nginx-tls-add
    - cryptpad

- name: Mumble
  hosts: localhost
  connection: local
  become: yes
  vars_files:
    - vars.yml
  tags:
    - mumble
    - never
  vars:
    nginx_domain_name: "mumble.{{ main_domain }}"
  roles:
    - nginx-tls-add
    - mumble

- name: Collabora
  hosts: localhost
  connection: local
  become: yes
  vars_files:
    - vars.yml
  tags:
    - collabora
    - never
  vars:
    nginx_domain_name: "collabora.{{ main_domain }}"
  roles:
    - nginx-tls-add
    - collabora

- name: Deploy mailserver
  collections:
    - community.docker
  hosts: localhost
  connection: local
  become: yes
  tags:
    - mail
    - never
  vars_files:
    - vars.yml
  vars:
    main_domain_name: "{{ main_domain }}"
    restic_to_backup: "/srv/mailserver"
    project_root: "/srv/mailserver"
  roles:
    - restic
    - docker
    - mailserver

- name: Ensure restic
  hosts: all
  become: yes
  tags: restic
  roles:
    - restic

- name: Secure the ssh server
  hosts: localhost
  connection: local
  become: yes
  vars_files:
    - vars.yml
  tags:
    - security
    - never
  roles:
    - security

- name: Perform backup
  hosts: localhost
  connection: local
  become: yes
  vars:
    restic_to_backup: /srv
  tags:
    - backup
    - never
  roles:
    - restic