---
- name: Register variable
  set_fact:
    resitc_password_file: /root/RESTIC_PASSWORD
    restic_repo: /restic/backup

- name: Perform backup
  shell: "restic backup {{ restic_backup }}"
  become: yes
  environment:
    RESTIC_PASSWORD_FILE: "{{ resitc_password_file }}"
    RESTIC_REPOSITORY: "{{ restic_repo }}"
