---
- name: Check if restic PW file exists
  stat: 
    path: "{{ restic_password_file }}"
  register: restic_password

- import_tasks: initiate.yml
  when: restic_password.stat.exists == False

- name: Perform backup
  shell: "/snap/bin/restic backup {{ restic_to_backup }}"
  become: yes
  environment:
    RESTIC_PASSWORD_FILE: "{{ restic_password_file }}"
    RESTIC_REPOSITORY: "{{ restic_repo }}"
  when: restic_to_backup != None
