---
# mailserver release. Set to 'stable' to track the stable branch.
mailserver_release: RELEASE
# ensure docker-compose gets restarted on every run
restart_compose: false
# default mailserver user
default_user: postmaster
# setting deploy directory
project_root: /srv/mailserver
# mailserver user
mailserver_user: root
# mailserver configs
config_fail2ban: 1
config_log_trigger: daily_cron
config_postmaster: 
config_message_limit: 102400000
