---

- name: Install required packages for autoupdate
  apt:
    name:
      - unattended-upgrades
    cache_valid_time: 86400

- name: Ensure apt packages absent
  apt:
    name:
      - sendmail
    state: absent
    purge: yes

- name: Ensure absent sendmail service
  file:
    path: /etc/init.d/sendmail
    state: absent
  notify:
    - stop sendmail
    - reload systemd

- name: Enable automatic update / upgrade
  copy:
    content: |
      APT::Periodic::Update-Package-Lists "1";
      APT::Periodic::Unattended-Upgrade "1";
    dest: /etc/apt/apt.conf.d/20auto-upgrades

- name: Configure unattended upgrades
  template:
    src: templates/50unattended-upgrades
    dest: /etc/apt/apt.conf.d/50unattended-upgrades

...
