---
- name: reload nginx
  service:
    name: nginx
    state: reloaded

- name: compose down
  docker_compose:
    project_src: "{{ project_root }}"
    state: absent

- name: compose up
  docker_compose:
    project_src: "{{ project_root }}"
    state: present
    pull: yes


