---
- name: read-only mounts
  lineinfile:
    path: "{{ project_root }}/docker-compose.yml"
    state: "{{ item.state }}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  become: yes
  loop:
    - { regexp: '(.*)\$\{CONFIG\}/web:/config(.*)', line: '            - ${CONFIG}/web:/config:ro', state: "present" }
  notify:
    - compose down
    - compose up

- name: ensure lastN settings
  blockinfile:
    path: "{{ project_root }}/data/web/config.js"
    insertafter: "    // lastNLimits: {"
    marker: '// {mark} Ansible managed Block'
    block: |
        lastNLimits: {
            5: 20,
            30: 15,
            50: 10,
            70: 5,
            90: 2
        },
  notify:
    - compose down
    - compose up

- name: Ensure config.js configs
  lineinfile:
    path: "{{ project_root }}/data/web/config.js"
    state: "{{ item.state }}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  become: yes
  loop:
    - { regexp: '(.*)startAudioMuted:(.*)', line: 'startAudioMuted: {{ config_start_audio_N }},', state: "present" }
    - { regexp: '(.*)startWithAudioMuted:(.*)', line: 'startWithAudioMuted: {{ config_start_muted_audio }},', state: "present" }
    - { regexp: '(.*)startAudioOnly:(.*)', line: 'startAudioOnly: {{ config_start_muted_audio }},', state: "present" }
    - { regexp: '(.*)startVideoMuted:(.*)', line: 'startVideoMuted: {{ config_start_video_N }},', state: "present" }
    - { regexp: '(.*)startWithVideoMuted:(.*)', line: 'startWithVideoMuted: {{ config_start_muted_video }},', state: "present" }
    - { regexp: '(.*)requireDisplayName:(.*)', line: 'requireDisplayName: {{ config_require_name }},', state: "present" }
    - { regexp: '(.*)defaultLanguage:(.*)', line: 'defaultLanguage: ''{{ config_default_language }}'',', state: "present" }
    #
    - { regexp: '(.*)config.startAudioOnly(.*)', line: 'config.startAudioOnly = {{ config_start_muted_audio }};', state: "present" }
    - { regexp: '(.*)config.startAudioMuted(.*)', line: 'config.startAudioMuted = {{ config_start_audio_N }};', state: "present" }
    - { regexp: '(.*)config.startVideoMuted(.*)', line: 'config.startVideoMuted = {{ config_start_video_N }};', state: "present" }
    - { regexp: '(.*)config.requireDisplayName(.*)', line: 'config.requireDisplayName = {{ config_require_name }};', state: "present" }
  notify:
    - compose down
    - compose up

- name: Ensure interface.js configs for logo
  lineinfile:
    path: "{{ project_root }}/data/web/interface_config.js"
    state: "{{ item.state }}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  become: yes
  loop:
    - { regexp: '(.*)DEFAULT_LOGO_URL(.*)', line: 'DEFAULT_LOGO_URL: ''{{ config_logo_url }}'',', state: "present" }
    - { regexp: '(.*)DEFAULT_WELCOME_PAGE_LOGO_URL(.*)', line: 'DEFAULT_WELCOME_PAGE_LOGO_URL: ''{{ config_logo_url }}'',', state: "present" }
  when: config_logo_file == None
  notify:
    - compose down
    - compose up

- name: Ensure interface.js configs
  lineinfile:
    path: "{{ project_root }}/data/web/interface_config.js"
    state: "{{ item.state }}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  become: yes
  loop:
    - { regexp: '(.*)DEFAULT_REMOTE_DISPLAY_NAME(.*)', line: 'DEFAULT_REMOTE_DISPLAY_NAME: ''{{ config_unnamed_user }}'',', state: "present" }
    - { regexp: '(.*)APP_NAME(.*)', line: 'APP_NAME: ''{{ config_name }}'',', state: "present" }
    - { regexp: '(.*)OPTIMAL_BROWSERS(.*)', line: 'OPTIMAL_BROWSERS: {{ config_optimal_browsers }},', state: "present" }
    - { regexp: '(.*)UNSUPPORTED_BROWSERS(.*)', line: 'UNSUPPORTED_BROWSERS: {{ config_unsupported_browsers }},', state: "present" }
    - { regexp: '(.*)SUPPORT_URL(.*)', line: 'SUPPORT_URL: ''{{ config_support_url }}'',', state: "present" }
    - { regexp: '(.*)JITSI_WATERMARK_LINK(.*)', line: 'JITSI_WATERMARK_LINK: ''{{ config_support_url }}'',', state: "present" }
  notify:
    - compose down
    - compose up

- import_tasks: logo.yml
  when: config_logo_file != None